"""
WICL IR Optimizer
=================
Stage 6 of the compiler pipeline.

Receives an IRResult generated by Stage 5 and applies semantics-preserving
optimizations to simplify and streamline execution.

Optimization Passes:
  1. Redundant Entity Load Elimination (deduplicates repeated LOAD_ITEM / LOAD_WAREHOUSE)
  2. Duplicate Read Check Elimination (deduplicates identical consecutive CHECK_STOCK / CHECK_CAPACITY)
  3. Compatible Credit/Debit Merging (combines consecutive CREDIT or DEBIT instructions for same target)

Guarantees:
  - NEVER alters program semantics, transaction boundaries, or audit invariants.
  - Returns both original and optimized IR so the UI can highlight changes.
"""
import time
from dataclasses import dataclass, field
from typing import List, Optional
from .ir_generator import IRInstruction, IRResult


@dataclass
class OptimizationNote:
    """Record of a specific optimization pass performed."""
    pass_name: str
    description: str
    lines_saved: int


@dataclass
class OptimizedIRResult:
    """Result of IR optimization."""
    success: bool
    command_type: str
    original_instructions: List[IRInstruction]
    optimized_instructions: List[IRInstruction]
    optimizations: List[OptimizationNote] = field(default_factory=list)
    reduction_count: int = 0
    optimization_time_ms: float = 0.0

    def to_dict(self) -> dict:
        return {
            "status": "success" if self.success else "error",
            "command_type": self.command_type,
            "original_count": len(self.original_instructions),
            "optimized_count": len(self.optimized_instructions),
            "reduction_count": self.reduction_count,
            "optimizations": [
                {
                    "pass_name": o.pass_name,
                    "description": o.description,
                    "lines_saved": o.lines_saved,
                }
                for o in self.optimizations
            ],
            "original_text": self._text_from(self.original_instructions, "Original IR"),
            "optimized_text": self._text_from(self.optimized_instructions, "Optimized IR"),
            "instructions": [i.to_dict() for i in self.optimized_instructions],
            "optimization_time_ms": round(self.optimization_time_ms, 4),
        }

    def _text_from(self, instrs: List[IRInstruction], label: str) -> str:
        lines = [f"; {label} ({len(instrs)} instructions)"]
        lines.append("; " + "─" * 40)
        for i, instr in enumerate(instrs):
            lines.append(f"{i:>3}:  {instr.to_text()}")
        return "\n".join(lines)


class IROptimizer:
    """
    Optimizes a sequence of IRInstructions safely.
    Call optimize(ir_result) to produce an OptimizedIRResult.
    """

    def optimize(self, ir_result: IRResult) -> OptimizedIRResult:
        t_start = time.perf_counter()

        if not ir_result.success or not ir_result.instructions:
            return OptimizedIRResult(
                success=ir_result.success,
                command_type=ir_result.command_type,
                original_instructions=ir_result.instructions or [],
                optimized_instructions=ir_result.instructions or [],
                optimization_time_ms=(time.perf_counter() - t_start) * 1000,
            )

        current = list(ir_result.instructions)
        notes: List[OptimizationNote] = []

        # Pass 1: Deduplicate redundant LOAD instructions
        current, p1_note = self._pass_dedup_loads(current)
        if p1_note:
            notes.append(p1_note)

        # Pass 2: Deduplicate redundant read checks
        current, p2_note = self._pass_dedup_checks(current)
        if p2_note:
            notes.append(p2_note)

        # Pass 3: Combine consecutive compatible CREDIT / DEBIT ops
        current, p3_note = self._pass_merge_credits(current)
        if p3_note:
            notes.append(p3_note)

        elapsed = (time.perf_counter() - t_start) * 1000
        lines_saved = len(ir_result.instructions) - len(current)

        return OptimizedIRResult(
            success=True,
            command_type=ir_result.command_type,
            original_instructions=ir_result.instructions,
            optimized_instructions=current,
            optimizations=notes,
            reduction_count=lines_saved,
            optimization_time_ms=round(elapsed, 4),
        )

    # ── Pass 1: Deduplicate LOAD_ITEM / LOAD_WAREHOUSE ────────────────────────
    def _pass_dedup_loads(self, instrs: List[IRInstruction]):
        seen_loads = set()
        new_instrs = []
        saved = 0

        for instr in instrs:
            if instr.opcode in ("LOAD_ITEM", "LOAD_WAREHOUSE"):
                key = (instr.opcode, instr.operand1)
                if key in seen_loads:
                    saved += 1
                    continue
                seen_loads.add(key)
            new_instrs.append(instr)

        note = None
        if saved > 0:
            note = OptimizationNote(
                pass_name="Entity Load Deduplication",
                description=f"Eliminated {saved} redundant entity resolution instruction(s)",
                lines_saved=saved,
            )
        return new_instrs, note

    # ── Pass 2: Deduplicate CHECK_STOCK / CHECK_CAPACITY ──────────────────────
    def _pass_dedup_checks(self, instrs: List[IRInstruction]):
        seen_checks = set()
        new_instrs = []
        saved = 0

        for instr in instrs:
            if instr.opcode in ("CHECK_STOCK", "CHECK_CAPACITY", "QUERY_STOCK"):
                key = (instr.opcode, instr.operand1, instr.operand2, instr.operand3)
                if key in seen_checks:
                    saved += 1
                    continue
                seen_checks.add(key)
            elif instr.opcode in ("DEBIT", "CREDIT", "SET_STOCK"):
                # Mutation invalidates cached check states
                seen_checks.clear()
            new_instrs.append(instr)

        note = None
        if saved > 0:
            note = OptimizationNote(
                pass_name="Redundant Check Elimination",
                description=f"Removed {saved} redundant validation check(s)",
                lines_saved=saved,
            )
        return new_instrs, note

    # ── Pass 3: Combine consecutive CREDIT / DEBIT ops ────────────────────────
    def _pass_merge_credits(self, instrs: List[IRInstruction]):
        new_instrs = []
        saved = 0
        i = 0

        while i < len(instrs):
            curr = instrs[i]
            if curr.opcode in ("CREDIT", "DEBIT") and i + 1 < len(instrs):
                nxt = instrs[i + 1]
                if (
                    nxt.opcode == curr.opcode
                    and nxt.operand1 == curr.operand1
                    and nxt.operand2 == curr.operand2
                    and curr.operand3
                    and nxt.operand3
                    and curr.operand3.isdigit()
                    and nxt.operand3.isdigit()
                ):
                    total_qty = int(curr.operand3) + int(nxt.operand3)
                    merged = IRInstruction(
                        opcode=curr.opcode,
                        operand1=curr.operand1,
                        operand2=curr.operand2,
                        operand3=str(total_qty),
                        comment=f"Optimized: Merged {curr.operand3} + {nxt.operand3} → {total_qty}",
                    )
                    new_instrs.append(merged)
                    saved += 1
                    i += 2
                    continue
            new_instrs.append(curr)
            i += 1

        note = None
        if saved > 0:
            note = OptimizationNote(
                pass_name="Operation Merging",
                description=f"Merged {saved} consecutive compatible inventory operation(s)",
                lines_saved=saved,
            )
        return new_instrs, note
